/*
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by FreeRTOS-OS/scripts/gen_irq_table.py from app/board/irq_table.xml
 * 2026-04-21 12:50 UTC
 *
 * This file is part of FreeRTOS-OS Project.
 */

#ifndef APP_BOARD_IRQ_HW_INIT_GENERATED_H_
#define APP_BOARD_IRQ_HW_INIT_GENERATED_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * irq_hw_init_all — initialise the irq_desc table, bind irq_chip_nvic to
 *                   every hardware-backed software IRQ ID, and configure NVIC
 *                   priorities.
 *
 * Call once at boot before any request_irq() or drv_irq_register() calls.
 * Generated from app/board/irq_table.xml by scripts/gen_irq_table.py.
 */
void irq_hw_init_all(void);

#ifdef __cplusplus
}
#endif

#endif /* APP_BOARD_IRQ_HW_INIT_GENERATED_H_ */
