/*
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by FreeRTOS-OS/scripts/gen_irq_table.py from app/board/irq_table.xml
 * 2026-04-23 14:50 UTC
 *
 * This file is part of FreeRTOS-OS Project.
 */
#include <board/board_config.h>

#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)

#include <device.h>
#include <drivers/drv_irq.h>
#include <drivers/hal/stm32/hal_iic_stm32.h>
#include <drivers/hal/stm32/hal_spi_stm32.h>
#include <drivers/hal/stm32/hal_uart_stm32.h>
#include <drivers/hal/stm32/hal_timebase_stm32.h>

#define _EXTI_DISPATCH(pin_mask, exti_line_idx)          \
    do {                                                 \
        BaseType_t _hpt = pdFALSE;                       \
        if (__HAL_GPIO_EXTI_GET_IT(pin_mask)) {          \
            __HAL_GPIO_EXTI_CLEAR_IT(pin_mask);          \
            uint16_t _pin = (pin_mask);                  \
            drv_irq_dispatch_from_isr(                   \
                IRQ_ID_EXTI(exti_line_idx), &_pin, &_hpt); \
        }                                                \
        portYIELD_FROM_ISR(_hpt);                        \
    } while (0)

/* ── Watchdog / Power ─────────────────────────────────────── */

void WWDG_IRQHandler(void) {}
void PVD_IRQHandler(void) {}
/* ── RTC / Tamper ─────────────────────────────────────────── */

void TAMP_STAMP_IRQHandler(void) {}
void RTC_WKUP_IRQHandler(void) {}
/* ── Flash ────────────────────────────────────────────────── */

void FLASH_IRQHandler(void) {}
/* ── RCC ──────────────────────────────────────────────────── */

void RCC_IRQHandler(void) {}
/* ── EXTI — individual lines ──────────────────────────────── */

void EXTI0_IRQHandler(void) { _EXTI_DISPATCH(GPIO_PIN_0, 0); }
void EXTI1_IRQHandler(void) { _EXTI_DISPATCH(GPIO_PIN_1, 1); }
void EXTI2_IRQHandler(void) { _EXTI_DISPATCH(GPIO_PIN_2, 2); }
void EXTI3_IRQHandler(void) { _EXTI_DISPATCH(GPIO_PIN_3, 3); }
void EXTI4_IRQHandler(void) { _EXTI_DISPATCH(GPIO_PIN_4, 4); }
/* ── DMA1 streams ─────────────────────────────────────────── */

void DMA1_Stream0_IRQHandler(void) {}
void DMA1_Stream1_IRQHandler(void) {}
void DMA1_Stream2_IRQHandler(void) {}
void DMA1_Stream3_IRQHandler(void) {}
void DMA1_Stream4_IRQHandler(void) {}
void DMA1_Stream5_IRQHandler(void) {}
void DMA1_Stream6_IRQHandler(void) {}
/* ── ADC ──────────────────────────────────────────────────── */

void ADC_IRQHandler(void) {}
/* ── EXTI — shared groups ─────────────────────────────────── */

void EXTI9_5_IRQHandler(void)
{
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_5);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_6);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_7);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_8);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_9);
}

/* ── Timers ───────────────────────────────────────────────── */

void TIM1_BRK_TIM9_IRQHandler(void) {}
/* TIM1_UP_TIM10 */
void TIM1_UP_TIM10_IRQHandler(void)
{
    hal_timebase_stm32_irq_handler();
}

void TIM1_TRG_COM_TIM11_IRQHandler(void) {}
void TIM1_CC_IRQHandler(void) {}
void TIM2_IRQHandler(void) {}
void TIM3_IRQHandler(void) {}
void TIM4_IRQHandler(void) {}
/* ── I2C ──────────────────────────────────────────────────── */

#ifdef HAL_I2C_MODULE_ENABLED

/* I2C_SENSOR — I2C1 */
void I2C1_EV_IRQHandler(void) { hal_iic_stm32_ev_irq_handler(I2C1); }
void I2C1_ER_IRQHandler(void) { hal_iic_stm32_er_irq_handler(I2C1); }

#endif /* HAL_I2C_MODULE_ENABLED */

void I2C2_EV_IRQHandler(void) {}
void I2C2_ER_IRQHandler(void) {}
/* ── SPI ──────────────────────────────────────────────────── */

#ifdef HAL_SPI_MODULE_ENABLED

/* SPI_FLASH — SPI1 */
void SPI1_IRQHandler(void) { hal_spi_stm32_irq_handler(SPI1); }

#endif /* HAL_SPI_MODULE_ENABLED */

void SPI2_IRQHandler(void) {}
/* ── UART ─────────────────────────────────────────────────── */

/* UART_DEBUG — USART1 */
void USART1_IRQHandler(void) { hal_uart_stm32_irq_handler(USART1); }

/* UART_APP — USART2 */
void USART2_IRQHandler(void) { hal_uart_stm32_irq_handler(USART2); }

/* ── EXTI — shared groups ─────────────────────────────────── */

void EXTI15_10_IRQHandler(void)
{
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_10);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_11);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_12);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_13);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_14);
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_15);
}

/* ── RTC / Tamper ─────────────────────────────────────────── */

void RTC_Alarm_IRQHandler(void) {}
/* ── USB OTG ──────────────────────────────────────────────── */

void OTG_FS_WKUP_IRQHandler(void) {}
/* ── DMA1 streams ─────────────────────────────────────────── */

void DMA1_Stream7_IRQHandler(void) {}
/* ── SDIO ─────────────────────────────────────────────────── */

void SDIO_IRQHandler(void) {}
/* ── Timers ───────────────────────────────────────────────── */

void TIM5_IRQHandler(void) {}
/* ── SPI ──────────────────────────────────────────────────── */

void SPI3_IRQHandler(void) {}
/* ── DMA2 streams ─────────────────────────────────────────── */

void DMA2_Stream0_IRQHandler(void) {}
void DMA2_Stream1_IRQHandler(void) {}
void DMA2_Stream2_IRQHandler(void) {}
void DMA2_Stream3_IRQHandler(void) {}
void DMA2_Stream4_IRQHandler(void) {}
/* ── USB OTG ──────────────────────────────────────────────── */

void OTG_FS_IRQHandler(void) {}
/* ── DMA2 streams ─────────────────────────────────────────── */

void DMA2_Stream5_IRQHandler(void) {}
void DMA2_Stream6_IRQHandler(void) {}
void DMA2_Stream7_IRQHandler(void) {}
/* ── UART ─────────────────────────────────────────────────── */

void USART6_IRQHandler(void) {}
/* ── I2C ──────────────────────────────────────────────────── */

void I2C3_EV_IRQHandler(void) {}
void I2C3_ER_IRQHandler(void) {}
/* ── FPU ──────────────────────────────────────────────────── */

void FPU_IRQHandler(void) {}
/* ── SPI ──────────────────────────────────────────────────── */

void SPI4_IRQHandler(void) {}
void SPI5_IRQHandler(void) {}

#endif /* CONFIG_DEVICE_VARIANT == MCU_VAR_STM */
