/*
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by FreeRTOS-OS/scripts/gen_irq_table.py from app/board/irq_table.xml
 * 2026-04-23 14:50 UTC
 *
 * This file is part of FreeRTOS-OS Project.
 */
#include <board/mcu_config.h>

#if (CONFIG_DEVICE_VARIANT == MCU_VAR_STM)

#include <device.h>
#include <irq/irq_desc.h>
#include <drivers/hal/stm32/irq_chip_nvic.h>

void irq_hw_init_all(void)
{
    irq_desc_init_all();

    /* ── Bind irq_chip_nvic to software IRQ IDs ──────────────────────── */

    /* UART_DEBUG — USART1_IRQn, priority 5 */
    irq_set_chip_and_handler(IRQ_ID_UART_RX(0)           , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_UART_TX_DONE(0)      , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_UART_ERROR(0)        , irq_chip_nvic_get(), handle_simple_irq);

    /* UART_APP — USART2_IRQn, priority 5 */
    irq_set_chip_and_handler(IRQ_ID_UART_RX(1)           , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_UART_TX_DONE(1)      , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_UART_ERROR(1)        , irq_chip_nvic_get(), handle_simple_irq);

    /* I2C_SENSOR — I2C1_EV_IRQn, priority 5 */
    irq_set_chip_and_handler(IRQ_ID_I2C_TX_DONE(0)       , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_I2C_RX_DONE(0)       , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_I2C_ERROR(0)         , irq_chip_nvic_get(), handle_simple_irq);

    /* SPI_FLASH — SPI1_IRQn, priority 5 */
    irq_set_chip_and_handler(IRQ_ID_SPI_TX_DONE(0)       , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_SPI_RX_DONE(0)       , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_SPI_TXRX_DONE(0)     , irq_chip_nvic_get(), handle_simple_irq);
    irq_set_chip_and_handler(IRQ_ID_SPI_ERROR(0)         , irq_chip_nvic_get(), handle_simple_irq);

    /* BTN_USER — EXTI0_IRQn, priority 6 */
    irq_set_chip_and_handler(IRQ_ID_EXTI(0)              , irq_chip_nvic_get(), handle_simple_irq);

    /* ── Set NVIC priorities for hardware IRQ lines ──────────────────── */

    /* UART_DEBUG — USART1_IRQn */
    irq_chip_nvic_bind_hwirq(IRQ_ID_UART_RX(0)           , USART1_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_UART_TX_DONE(0)      , USART1_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_UART_ERROR(0)        , USART1_IRQn, 5U);

    /* UART_APP — USART2_IRQn */
    irq_chip_nvic_bind_hwirq(IRQ_ID_UART_RX(1)           , USART2_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_UART_TX_DONE(1)      , USART2_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_UART_ERROR(1)        , USART2_IRQn, 5U);

    /* I2C_SENSOR — I2C1_EV_IRQn */
    irq_chip_nvic_bind_hwirq(IRQ_ID_I2C_TX_DONE(0)       , I2C1_EV_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_I2C_RX_DONE(0)       , I2C1_EV_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_I2C_ERROR(0)         , I2C1_ER_IRQn, 5U);

    /* SPI_FLASH — SPI1_IRQn */
    irq_chip_nvic_bind_hwirq(IRQ_ID_SPI_TX_DONE(0)       , SPI1_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_SPI_RX_DONE(0)       , SPI1_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_SPI_TXRX_DONE(0)     , SPI1_IRQn, 5U);
    irq_chip_nvic_bind_hwirq(IRQ_ID_SPI_ERROR(0)         , SPI1_IRQn, 5U);

    /* BTN_USER — EXTI0_IRQn */
    irq_chip_nvic_bind_hwirq(IRQ_ID_EXTI(0)              , EXTI0_IRQn, 6U);

    /* ── System / core IRQ priorities ────────────────────────────────── */

    /* SysTick */
    HAL_NVIC_SetPriority(SysTick_IRQn, 15U, 0U);

    /* PendSV */
    HAL_NVIC_SetPriority(PendSV_IRQn, 15U, 0U);

    /* SVCall */
    HAL_NVIC_SetPriority(SVCall_IRQn, 14U, 0U);

    /* TIM1_UP_TIM10 */
    HAL_NVIC_SetPriority(TIM1_UP_TIM10_IRQn, 1U, 0U);
    HAL_NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);

    /* ── Bind irq_chip_nvic to system IRQ IDs ────────────────────────── */

    /* TIM_TICK — TIM1_UP_TIM10_IRQn, priority 1, edge flow */
    irq_set_chip_and_handler(IRQ_ID_TIM_TICK             , irq_chip_nvic_get(), handle_edge_irq);
    irq_chip_nvic_bind_hwirq(IRQ_ID_TIM_TICK             , TIM1_UP_TIM10_IRQn, 1U);
}

#endif /* CONFIG_DEVICE_VARIANT == MCU_VAR_STM */
