/*
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by FreeRTOS-OS/scripts/gen_irq_table.py from app/board/irq_table.xml
 * 2026-06-23 07:31 UTC
 *
 * This file is part of FreeRTOS-OS Project.
 */
#ifndef APP_BOARD_IRQ_PERIPH_HANDLERS_GENERATED_H_
#define APP_BOARD_IRQ_PERIPH_HANDLERS_GENERATED_H_

/*
 * Peripheral IRQ handler weak forward declarations.
 * Include ONLY from the startup compilation unit where
 * Default_Handler is defined in the same translation unit.
 */

void WWDG_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void PVD_AVD_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void RTC_TAMP_STAMP_CSS_LSE_IRQHandler(void)         __attribute__((weak, alias("Default_Handler"), used));
void RTC_WKUP_IRQHandler(void)                       __attribute__((weak, alias("Default_Handler"), used));
void FLASH_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void RCC_IRQHandler(void)                            __attribute__((weak, alias("Default_Handler"), used));
void EXTI0_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void EXTI1_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void EXTI2_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void EXTI3_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void EXTI4_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream0_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream1_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream2_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream3_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream4_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream5_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream6_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void ADC_IRQHandler(void)                            __attribute__((weak, alias("Default_Handler"), used));
void FDCAN1_IT0_IRQHandler(void)                     __attribute__((weak, alias("Default_Handler"), used));
void FDCAN2_IT0_IRQHandler(void)                     __attribute__((weak, alias("Default_Handler"), used));
void FDCAN1_IT1_IRQHandler(void)                     __attribute__((weak, alias("Default_Handler"), used));
void FDCAN2_IT1_IRQHandler(void)                     __attribute__((weak, alias("Default_Handler"), used));
void EXTI9_5_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void TIM1_BRK_IRQHandler(void)                       __attribute__((weak, alias("Default_Handler"), used));
void TIM1_UP_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void TIM1_TRG_COM_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void TIM1_CC_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void TIM2_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void TIM3_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void TIM4_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void I2C1_EV_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void I2C1_ER_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void I2C2_EV_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void I2C2_ER_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void SPI1_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void SPI2_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void USART1_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void USART2_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void USART3_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void EXTI15_10_IRQHandler(void)                      __attribute__((weak, alias("Default_Handler"), used));
void RTC_Alarm_IRQHandler(void)                      __attribute__((weak, alias("Default_Handler"), used));
void TIM8_BRK_TIM12_IRQHandler(void)                 __attribute__((weak, alias("Default_Handler"), used));
void TIM8_UP_TIM13_IRQHandler(void)                  __attribute__((weak, alias("Default_Handler"), used));
void TIM8_TRG_COM_TIM14_IRQHandler(void)             __attribute__((weak, alias("Default_Handler"), used));
void TIM8_CC_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void DMA1_Stream7_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void SDMMC1_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void TIM5_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void SPI3_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void UART4_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void UART5_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void TIM6_DAC_IRQHandler(void)                       __attribute__((weak, alias("Default_Handler"), used));
void TIM7_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream0_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream1_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream2_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream3_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream4_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void ETH_IRQHandler(void)                            __attribute__((weak, alias("Default_Handler"), used));
void ETH_WKUP_IRQHandler(void)                       __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream5_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream6_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void DMA2_Stream7_IRQHandler(void)                   __attribute__((weak, alias("Default_Handler"), used));
void USART6_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void I2C3_EV_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void I2C3_ER_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void FPU_IRQHandler(void)                            __attribute__((weak, alias("Default_Handler"), used));
void UART7_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void UART8_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void SPI4_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void SPI5_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void SPI6_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void LPTIM1_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void I2C4_EV_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void I2C4_ER_IRQHandler(void)                        __attribute__((weak, alias("Default_Handler"), used));
void TIM15_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void TIM16_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void TIM17_IRQHandler(void)                          __attribute__((weak, alias("Default_Handler"), used));
void MDMA_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));
void LPTIM2_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void LPTIM3_IRQHandler(void)                         __attribute__((weak, alias("Default_Handler"), used));
void FMAC_IRQHandler(void)                           __attribute__((weak, alias("Default_Handler"), used));

#endif /* APP_BOARD_IRQ_PERIPH_HANDLERS_GENERATED_H_ */
