/*
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by FreeRTOS-OS/scripts/gen_irq_table.py from app/board/irq_table.xml
 * 2026-04-23 14:50 UTC
 *
 * This file is part of FreeRTOS-OS Project.
 */

#ifndef APP_BOARD_IRQ_HW_CONF_H_
#define APP_BOARD_IRQ_HW_CONF_H_

#include <stdint.h>

/* ── Capacity constants ──────────────────────────────────────────────────── */

#define IRQ_MAX_UART            4    /* max UART bus instances     */
#define IRQ_MAX_I2C             4    /* max I2C bus instances      */
#define IRQ_MAX_SPI             4    /* max SPI bus instances      */
#define IRQ_MAX_EXTI_LINES      16   /* GPIO EXTI lines 0-15     */

#define IRQ_UART_EVENTS         3    /* RX, TX_DONE, ERROR         */
#define IRQ_I2C_EVENTS          3    /* TX_DONE, RX_DONE, ERROR    */
#define IRQ_SPI_EVENTS          4    /* TX_DONE, RX_DONE, TXRX, ERR */

#define IRQ_NOTIFY_MAX_SUBS     4    /* subscribers per IRQ ID     */

/* ── IRQ ID base offsets ─────────────────────────────────────────────────── */

#define IRQ_ID_UART_BASE   0
#define IRQ_ID_I2C_BASE    (IRQ_ID_UART_BASE + IRQ_MAX_UART * IRQ_UART_EVENTS)
#define IRQ_ID_SPI_BASE    (IRQ_ID_I2C_BASE  + IRQ_MAX_I2C  * IRQ_I2C_EVENTS)
#define IRQ_ID_EXTI_BASE   (IRQ_ID_SPI_BASE  + IRQ_MAX_SPI  * IRQ_SPI_EVENTS)

/* ── System IRQ IDs (allocated after EXTI block) ────────────────────── */

#define IRQ_ID_SYS_BASE    (IRQ_ID_EXTI_BASE + IRQ_MAX_EXTI_LINES)
#define IRQ_ID_TIM_TICK         ((irq_id_t)(IRQ_ID_SYS_BASE + 0))

#define IRQ_ID_TOTAL       (IRQ_ID_SYS_BASE + 1)

typedef uint32_t irq_id_t;

/* ── ID generator macros ─────────────────────────────────────────────────── */

#define IRQ_ID_UART_RX(n)        ((irq_id_t)(IRQ_ID_UART_BASE + (n)*IRQ_UART_EVENTS + 0))
#define IRQ_ID_UART_TX_DONE(n)   ((irq_id_t)(IRQ_ID_UART_BASE + (n)*IRQ_UART_EVENTS + 1))
#define IRQ_ID_UART_ERROR(n)     ((irq_id_t)(IRQ_ID_UART_BASE + (n)*IRQ_UART_EVENTS + 2))

#define IRQ_ID_I2C_TX_DONE(n)    ((irq_id_t)(IRQ_ID_I2C_BASE  + (n)*IRQ_I2C_EVENTS  + 0))
#define IRQ_ID_I2C_RX_DONE(n)    ((irq_id_t)(IRQ_ID_I2C_BASE  + (n)*IRQ_I2C_EVENTS  + 1))
#define IRQ_ID_I2C_ERROR(n)      ((irq_id_t)(IRQ_ID_I2C_BASE  + (n)*IRQ_I2C_EVENTS  + 2))

#define IRQ_ID_SPI_TX_DONE(n)    ((irq_id_t)(IRQ_ID_SPI_BASE  + (n)*IRQ_SPI_EVENTS  + 0))
#define IRQ_ID_SPI_RX_DONE(n)    ((irq_id_t)(IRQ_ID_SPI_BASE  + (n)*IRQ_SPI_EVENTS  + 1))
#define IRQ_ID_SPI_TXRX_DONE(n)  ((irq_id_t)(IRQ_ID_SPI_BASE  + (n)*IRQ_SPI_EVENTS  + 2))
#define IRQ_ID_SPI_ERROR(n)      ((irq_id_t)(IRQ_ID_SPI_BASE  + (n)*IRQ_SPI_EVENTS  + 3))

/** IRQ_ID_EXTI(pin) — GPIO EXTI line interrupt, pin in [0, 15]. */
#define IRQ_ID_EXTI(pin)         ((irq_id_t)(IRQ_ID_EXTI_BASE + (pin)))

#endif /* APP_BOARD_IRQ_HW_CONF_H_ */
