/*
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by FreeRTOS-OS/scripts/gen_irq_table.py from app/board/irq_table.xml
 * 2026-04-23 14:50 UTC
 *
 * This file is part of FreeRTOS-OS Project.
 */
#include <irq/irq_table.h>
static const char * const _irq_names[IRQ_ID_TOTAL] = {

    /* ── UART ──────────────────────────────────────────────────────── */
    [IRQ_ID_UART_RX(0)           ] = "UART_DEBUG_RX",
    [IRQ_ID_UART_TX_DONE(0)      ] = "UART_DEBUG_TX_DONE",
    [IRQ_ID_UART_ERROR(0)        ] = "UART_DEBUG_ERROR",

    [IRQ_ID_UART_RX(1)           ] = "UART_APP_RX",
    [IRQ_ID_UART_TX_DONE(1)      ] = "UART_APP_TX_DONE",
    [IRQ_ID_UART_ERROR(1)        ] = "UART_APP_ERROR",

    [IRQ_ID_UART_RX(2)           ] = "UART2_RX",
    [IRQ_ID_UART_TX_DONE(2)      ] = "UART2_TX_DONE",
    [IRQ_ID_UART_ERROR(2)        ] = "UART2_ERROR",

    [IRQ_ID_UART_RX(3)           ] = "UART3_RX",
    [IRQ_ID_UART_TX_DONE(3)      ] = "UART3_TX_DONE",
    [IRQ_ID_UART_ERROR(3)        ] = "UART3_ERROR",

    /* ── I2C ──────────────────────────────────────────────────────── */
    [IRQ_ID_I2C_TX_DONE(0)       ] = "I2C_SENSOR_TX_DONE",
    [IRQ_ID_I2C_RX_DONE(0)       ] = "I2C_SENSOR_RX_DONE",
    [IRQ_ID_I2C_ERROR(0)         ] = "I2C_SENSOR_ERROR",

    [IRQ_ID_I2C_TX_DONE(1)       ] = "I2C1_TX_DONE",
    [IRQ_ID_I2C_RX_DONE(1)       ] = "I2C1_RX_DONE",
    [IRQ_ID_I2C_ERROR(1)         ] = "I2C1_ERROR",

    [IRQ_ID_I2C_TX_DONE(2)       ] = "I2C2_TX_DONE",
    [IRQ_ID_I2C_RX_DONE(2)       ] = "I2C2_RX_DONE",
    [IRQ_ID_I2C_ERROR(2)         ] = "I2C2_ERROR",

    [IRQ_ID_I2C_TX_DONE(3)       ] = "I2C3_TX_DONE",
    [IRQ_ID_I2C_RX_DONE(3)       ] = "I2C3_RX_DONE",
    [IRQ_ID_I2C_ERROR(3)         ] = "I2C3_ERROR",

    /* ── SPI ──────────────────────────────────────────────────────── */
    [IRQ_ID_SPI_TX_DONE(0)       ] = "SPI_FLASH_TX_DONE",
    [IRQ_ID_SPI_RX_DONE(0)       ] = "SPI_FLASH_RX_DONE",
    [IRQ_ID_SPI_TXRX_DONE(0)     ] = "SPI_FLASH_TXRX_DONE",
    [IRQ_ID_SPI_ERROR(0)         ] = "SPI_FLASH_ERROR",

    [IRQ_ID_SPI_TX_DONE(1)       ] = "SPI1_TX_DONE",
    [IRQ_ID_SPI_RX_DONE(1)       ] = "SPI1_RX_DONE",
    [IRQ_ID_SPI_TXRX_DONE(1)     ] = "SPI1_TXRX_DONE",
    [IRQ_ID_SPI_ERROR(1)         ] = "SPI1_ERROR",

    [IRQ_ID_SPI_TX_DONE(2)       ] = "SPI2_TX_DONE",
    [IRQ_ID_SPI_RX_DONE(2)       ] = "SPI2_RX_DONE",
    [IRQ_ID_SPI_TXRX_DONE(2)     ] = "SPI2_TXRX_DONE",
    [IRQ_ID_SPI_ERROR(2)         ] = "SPI2_ERROR",

    [IRQ_ID_SPI_TX_DONE(3)       ] = "SPI3_TX_DONE",
    [IRQ_ID_SPI_RX_DONE(3)       ] = "SPI3_RX_DONE",
    [IRQ_ID_SPI_TXRX_DONE(3)     ] = "SPI3_TXRX_DONE",
    [IRQ_ID_SPI_ERROR(3)         ] = "SPI3_ERROR",

    /* ── GPIO EXTI lines ──────────────────────────────────────────── */
    [IRQ_ID_EXTI(0)              ] = "BTN_USER",
    [IRQ_ID_EXTI(1)              ] = "EXTI1",
    [IRQ_ID_EXTI(2)              ] = "EXTI2",
    [IRQ_ID_EXTI(3)              ] = "EXTI3",
    [IRQ_ID_EXTI(4)              ] = "EXTI4",
    [IRQ_ID_EXTI(5)              ] = "EXTI5",
    [IRQ_ID_EXTI(6)              ] = "EXTI6",
    [IRQ_ID_EXTI(7)              ] = "EXTI7",
    [IRQ_ID_EXTI(8)              ] = "EXTI8",
    [IRQ_ID_EXTI(9)              ] = "EXTI9",
    [IRQ_ID_EXTI(10)             ] = "EXTI10",
    [IRQ_ID_EXTI(11)             ] = "EXTI11",
    [IRQ_ID_EXTI(12)             ] = "EXTI12",
    [IRQ_ID_EXTI(13)             ] = "EXTI13",
    [IRQ_ID_EXTI(14)             ] = "EXTI14",
    [IRQ_ID_EXTI(15)             ] = "EXTI15",

    /* ── System IRQ IDs ───────────────────────────────────────────── */
    [IRQ_ID_TIM_TICK             ] = "TIM_TICK",
};

const char *irq_table_get_name(irq_id_t id)
{
    if (id >= IRQ_ID_TOTAL)
        return "INVALID";
    return _irq_names[id] ? _irq_names[id] : "UNKNOWN";
}
